import { Song } from '../types';

export const HATE_COMMENTS = [
  "This is the worst song ever",
  "My ears are bleeding",
  "Make it stop!",
  "Who actually likes this?",
  "I want my money back",
  "This should be illegal",
  "My brain hurts now",
  "Instant headache",
  "Why does this exist?",
  "Pure torture",
  "Kill it with fire!",
  "Unlistenable garbage",
  "My soul is dying",
  "Ear cancer confirmed",
  "Please end my suffering",
  "This is a crime against music",
  "I need therapy now",
  "My neighbors called the cops",
  "Even my dog is howling",
  "This violates the Geneva Convention",
  "I'm calling the police",
  "My therapist will hear about this",
  "This is psychological warfare",
  "I can't unhear this",
  "My ears filed a restraining order",
  "This is a hate crime against sound",
  "I need ear bleach ASAP",
  "My speakers are crying",
  "This is sonic terrorism",
  "I'm suing for emotional damage",
  "My ancestors are disappointed",
  "This is a public health hazard",
  "I lost my will to live",
  "My plants are wilting",
  "This is audio poison",
  "I'm moving to a different planet",
  "My doctor says no more",
  "This is a war crime",
  "I need a refund on life",
  "My cat left the house",
  "This is musical heresy",
  "I'm calling the FBI",
  "My ears are pressing charges",
  "This is aural assault",
  "I need emergency surgery",
  "My brain is melting",
  "This is sound pollution",
  "I'm going deaf intentionally",
  "My heart stopped beating",
  "This is acoustic violence",
];

export const SONGS: Song[] = [
  {
    id: 'baby-shark',
    title: 'Baby Shark',
    artist: 'Pinkfong',
    duration: 90,
    bpm: 120,
    hateRating: 9.8,
    difficulty: 'easy',
    color: '#FF6B9D',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: 'crazy-frog',
    title: 'Axel F',
    artist: 'Crazy Frog',
    duration: 120,
    bpm: 140,
    hateRating: 8.9,
    difficulty: 'medium',
    color: '#4ECDC4',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: 'gangnam-style',
    title: 'Gangnam Style',
    artist: 'PSY',
    duration: 150,
    bpm: 132,
    hateRating: 7.5,
    difficulty: 'hard',
    color: '#FFE66D',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: 'barbie-girl',
    title: 'Barbie Girl',
    artist: 'Aqua',
    duration: 105,
    bpm: 128,
    hateRating: 8.2,
    difficulty: 'medium',
    color: '#FF69B4',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: 'macarena',
    title: 'Macarena',
    artist: 'Los Del Rio',
    duration: 135,
    bpm: 104,
    hateRating: 7.8,
    difficulty: 'easy',
    color: '#FFA500',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: 'chicken-dance',
    title: 'Chicken Dance',
    artist: 'Werner Thomas',
    duration: 95,
    bpm: 116,
    hateRating: 9.2,
    difficulty: 'hard',
    color: '#FFD700',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
];

export const LANES = 4;
export const NOTE_SPEED = 280; // pixels per second
export const HIT_WINDOW = {
  perfect: 0.05,
  good: 0.12,
  miss: 0.2,
};
export const POINTS = {
  perfect: 100,
  good: 50,
  miss: 0,
};
